### ISSUE TITLE
Open existing file

### ISSUE THREAD

**Issue by funivan** [memio/memio#15]
Hi. Is there any way to open file and edit it with your code.
I see `building models from existing code (using nikic's PHP-Parser)` but possible there is a way to parse file according to token_get_all

For example symfony cs fixer use this approach https://github.com/FriendsOfPHP/PHP-CS-Fixer
I can help to implement this =)

**Comment by gnugat** [comment]
Hello @funivan, this is planned in the long term (probably for the beta version), but for now I'd like to consolidate the models:
- there's still a lot of things missing like default values for Argument and Property, we can't describe interfaces yet, etc
- the relationship between them are subject to changes (File should probably own License, and shouldn't be responsible for describing a class)
- some BC breaks might still happen (renaming methods, or changing the return values)

I'd also like to have a better and more complete way to manage meta data (mainly PHPdocs).

If we started to open existing files now, we'd lose too much information...
I've considered using PHP-CS-Fixer approach, but it'd require too much work that is already done by PHP Parser: creating a parser, a way to visit nodes and collect data... It'd probably more than double the code base size.
That's why I'd like to use PHP Parser, for example Qafoo Refactoring Browser uses this approach: https://github.com/QafooLabs/php-refactoring-browser

You'd be more than welcome to help, I think I'll start creating tickets so people know where they could help.
Thanks for your interest!

**Comment by gnugat** [comment]
Hey @funivan ! I've just created a whole bunch of tickets, if you'd like to work on any of them don't hesitate to write a comment in it (so I know which one I shouldn't work on).
I usually don't have internet when I work, my concern is that I pick an issue you'd pick but I'll try to mark in advance which ones I think I'll have to time to do.
Cheers!

**Comment by gnugat** [comment]
I'll close this ticket, and create a milestone.
