### ISSUE TITLE
Class extends dont support namespaces

### ISSUE THREAD

**Issue by ahoendgen** [memio/memio#75]
output of 
```php
$object = (new Object("Test\TestClass"))->extend(new Object("My\Fancy\Object"));
```
will be
```php
<?php

namespace Test;

class TestClass extends Object {
```
i would except it to be
```php
<?php

namespace Test;

class TestClass extends My\Fancy\Object {
```

**Comment by gnugat** [comment]
Hi @ahoendgen, and happy new year!
Sorry for the delay, I've spent my end of the year holidays entirely disconnected.

I know this behavior is surprising and sometimes annoying, but that's because of the current coding style followed by Memio: all namespaces classes should be declared using a `use` statement, so in your case you'd need to do something similar to:

```
$file = File::make('src/Test/TestClass')
    ->addFullyQualifiedName('My\Fancy\Object')
    ->setStructure(
      Object::make('Test\TestClass')
        ->extend(Object::make('My\Fancy\Object'))
    )
);
```

> *Note*: the `->addFullyQualifiedName('My\Fancy\Object')` call will generate a `use My\Fancy\Object;` line that fixes the issue.

It will generate the following code:

```
<?php

namespace Test;

use My\Fancy\Object;

class TestClass extends Object {
}
```

An alternative way to achieve the coding style you mentionned in your code snippet would be to create your own twig template (Memio is a highly opinionated tool, but it allows you to use your own opinions via templates that you can over write).

You'll find similar issue report here: #63 and #71, there's currently no plan to change it. I hope this answer will help you.

**Comment by ahoendgen** [comment]
ok, thx 4 info
